// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteInput struct {
	ID int `json:"id"`
}

type NewUser struct {
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Date      *string `json:"date"`
	Gender    *int    `json:"gender"`
	Password  string  `json:"password"`
}

type SearchUser struct {
	Name      *string `json:"name"`
	Email     *string `json:"email"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Date      *string `json:"date"`
	Gender    *int    `json:"gender"`
	Password  *string `json:"password"`
}

type UpdateUser struct {
	ID        int     `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Date      *string `json:"date"`
	Gender    *int    `json:"gender"`
	Password  string  `json:"password"`
}

type User struct {
	ID        int     `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Date      *string `json:"date"`
	Gender    *int    `json:"gender"`
	Password  string  `json:"password"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt *string `json:"updatedAt"`
	DeletedAt *string `json:"deletedAt"`
}
